services:
  - type: web
    name: proyecto-tecnica
    runtime: python  # Solo especifica 'python'
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production  # Si necesitas especificar el entorno
